=== FunProgramer/vocabulary-trainer-app/schema/vocabulary-collection.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Vocabulary Collection",
  "description": "A collection of vocabulary that can be imported into the vocabulary trainer app",
  "type": "object",
  "properties": {
    "title": {
      "description": "The title of the collection to be displayed by the app",
      "type": "string"
    },
    "languageA": {
      "description": "One ('the first') of the languages of which the vocabulary is in format of ISO 639-1.",
      "type": "string",
      "minLength": 2,
      "maxLength": 2
    },
    "languageB": {
      "description": "One ('the second') of the languages of which the vocabulary is in format of ISO 639-1.",
      "type": "string",
      "minLength": 2,
      "maxLength": 2
    },
    "vocabularies": {
      "description": "An array of the individual vocabulary objects",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "languageA": {
            "description": "The corresponding word in language A. If an answer exactly matches this String it's fully correct.",
            "type": "string"
          },
          "languageARegex": {
            "description": "The regex (JS dialect) to check if an answer is good enough to mark it as correct, in language A.",
            "type": "string"
          },
          "languageB": {
            "description": "The corresponding word in language B. If an answer exactly matches this String it's fully correct.",
            "type": "string"
          },
          "languageBRegex": {
            "description": "The regex (JS dialect) to check if an answer is good enough to mark it as correct, in language B.",
            "type": "string"
          }
        },
        "required": ["languageA", "languageARegex", "languageB", "languageBRegex"]
      }
    }
  },
  "required": ["title", "languageA", "languageB", "vocabularies"]
}

=== FunProgramer/vocabulary-trainer-app/example-vocabulary-collection.voc.json
{
  "$schema": "https://github.com/FunProgramer/vocabulary-trainer-app/raw/flutter-rewrite/schema/vocabulary-collection.schema.json",
  "title": "Unit 11 (Part 3)",
  "languageA": "en",
  "languageB": "de",
  "vocabularies": [
    {
      "languageA": "to re-shore",
      "languageARegex": "(to )?re-?shore",
      "languageB": "(Industrie) wieder im Inland ansiedeln, wieder ins Inland verlagern",
      "languageBRegex": "(\\(?Industrie\\)? )?(wieder im Inland ansiedeln|wieder ins Inland verlagern|wieder im Inland ansiedeln, wieder ins Inland verlagern)"
    },
    {
      "languageA": "head",
      "languageARegex": "head",
      "languageB": "Leiter/in, Chef/in",
      "languageBRegex": "(Leiter(/in)?|Chef(/in)?|Leiter/in, Chef/in)"
    }
  ]
}
